import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { handleApi } from '../server/worker.mjs';
const sqlite=new DatabaseSync(':memory:');
sqlite.exec(readFileSync('drizzle/0000_workable_vengeance.sql','utf8'));
const db={prepare(sql){return{args:[],bind(...args){this.args=args;return this;},async run(){const r=sqlite.prepare(sql).run(...this.args);return{meta:{changes:Number(r.changes)}};},async first(){return sqlite.prepare(sql).get(...this.args)??null;},async all(){return{results:sqlite.prepare(sql).all(...this.args)};}};},async batch(statements){return Promise.all(statements.map(s=>s.run()));}};
const pending=[];const ctx={waitUntil:p=>pending.push(p)};
const env={DB:db};
const request=(path,body,headers={})=>new Request('https://game.example/api/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','Origin':'https://game.example',...headers}:headers,body:body?JSON.stringify(body):undefined});
let response=await handleApi(request('config'),env,ctx);assert.equal((await response.json()).phoneReady,false);
response=await handleApi(request('runs',{}),env,ctx);assert.equal(response.status,201);const run=await response.json();
response=await handleApi(request('scores',{...run,name:'Тест',score:9999999,distance:5}),env,ctx);assert.equal(response.status,400);
response=await handleApi(request('scores',{...run,token:'wrong',name:'Тест',score:1,distance:1}),env,ctx);assert.equal(response.status,401);
response=await handleApi(request('scores',{...run,name:'Пилот ST9',score:1,distance:1}),env,ctx);assert.equal(response.status,200);
response=await handleApi(request('scores',{...run,name:'Повтор',score:1,distance:1}),env,ctx);assert.equal(response.status,401);
response=await handleApi(request('leaderboard'),env,ctx);const rows=(await response.json()).rows;assert.equal(rows.length,1);assert.equal(rows[0].name,'Пилот ST9');assert(!JSON.stringify(rows).includes('token'));
response=await handleApi(request('runs',{}, {'Origin':'https://evil.example'}),env,ctx);assert.equal(response.status,403);
const run2=await (await handleApi(request('runs',{}),env,ctx)).json();
response=await handleApi(request('leads',{...run2,phone:'+7 999 000-00-00',consent:true,continuation:1}),env,ctx);assert.equal(response.status,503);
env.CRM_WEBHOOK_URL='https://crm.example/webhook';env.PRIVACY_URL='https://dealer.example/privacy';
const oldFetch=globalThis.fetch;const deliveries=[];
globalThis.fetch=async(url,init)=>{deliveries.push(JSON.parse(init.body));return new Response('{}',{status:200});};
response=await handleApi(request('leads',{...run2,phone:'123',consent:true,continuation:1}),env,ctx);assert.equal(response.status,400);
response=await handleApi(request('leads',{...run2,phone:'+7 999 000-00-00',consent:false,continuation:1}),env,ctx);assert.equal(response.status,400);
const lead={...run2,phone:'+7 999 000-00-00',consent:true,continuation:1,score:12};
response=await handleApi(request('leads',lead),env,ctx);assert.equal(response.status,200);await Promise.all(pending);
response=await handleApi(request('leads',lead),env,ctx);assert.equal(response.status,200);await Promise.all(pending);
assert.equal(deliveries.length,1);assert.equal(deliveries[0].phone,'+79990000000');assert(deliveries[0].consent.accepted);
assert.equal(sqlite.prepare('SELECT crm_status FROM leads').get().crm_status,'delivered');
globalThis.fetch=async()=>{throw new Error('CRM offline');};
await handleApi(request('leads',{...lead,continuation:2}),env,ctx);await Promise.all(pending);
assert.equal(sqlite.prepare("SELECT COUNT(*) AS count FROM leads WHERE crm_status='pending'").get().count,1);
response=await handleApi(request('admin/leads'),env,ctx);assert.equal(response.status,401);
env.ADMIN_TOKEN='test-only';
response=await handleApi(request('admin/leads',undefined,{'Authorization':'Bearer test-only'}),env,ctx);assert.equal(response.status,200);
globalThis.fetch=oldFetch;sqlite.close();
console.log('PASS: shared scores, run authentication, validation, duplicate prevention, consent, CRM delivery and outage queue, private admin access. Test data used only an in-memory database and a mocked CRM.');
