import assert from 'node:assert/strict';
import ts from 'typescript';
import { readFileSync } from 'node:fs';
const modelJS=ts.transpile(readFileSync('src/game/model.ts','utf8'),{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020});
const mod={exports:{}};new Function('exports','module',modelJS)(mod.exports,mod);const model=mod.exports;
assert.equal(model.biomeAt(0),0);assert.equal(model.biomeAt(750),1);assert.equal(model.biomeAt(1500),2);assert.equal(model.biomeAt(2250),0);
assert(model.laneX(0,624)<model.laneX(1,624));assert(model.laneX(2,624)<430);
assert(model.roadHalf(780)>model.roadHalf(0));
let state={clock:0,distance:0,charge:100,boostUntil:0,ghostUntil:0};
for(let i=0;i<1200;i++)state=model.advanceRun(state,.05);
assert(state.distance>1500&&state.distance<2500);assert(state.charge===100);
const normal=model.advanceRun({clock:0,distance:0,charge:0,boostUntil:0,ghostUntil:0},.05);
const boosted=model.advanceRun({clock:0,distance:0,charge:0,boostUntil:4,ghostUntil:0},.05);
assert(boosted.speed>normal.speed);assert.equal(boosted.charge,0);
assert(model.hitTest(200,624,100,150,220,630,90,120));assert(!model.hitTest(100,624,100,150,300,624,90,120));
let sceneSource=readFileSync('src/game/scenes/TrafficScene.ts','utf8').replace(/^import .*;\r?\n/gm,'').replace('export class TrafficScene','class TrafficScene');
const sceneJS=ts.transpile(sceneSource,{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.None}).replace(/export \{\};?/g,'');
const Scene=new Function('exports','Phaser','assetUrl','PAINT_FILTERS',...Object.keys(model),sceneJS+';return TrafficScene;')({}, {Scene:class{}},x=>x,{},...Object.values(model));
let exhausted=0,lastHud;
const scene=new Scene({carColor:'#10161d',onHud:h=>lastHud=h,onExhausted:()=>exhausted++,onReady:()=>{},onError:()=>{}});
scene.cameras={main:{shake:()=>{}}};scene.game={events:{emit:()=>{}}};scene.tweens={pauseAll:()=>{},resumeAll:()=>{}};
scene.floatingText=()=>{};scene.player={};scene.run.clock=1;
scene.crash();assert.equal(scene.lives,2);assert.equal(scene.run.ghostUntil,3.8);
scene.crash();assert.equal(scene.lives,2,'No double damage during invincibility');
scene.run.clock=4;scene.crash();assert.equal(scene.lives,1);
scene.run.clock=7;scene.crash();assert.equal(scene.lives,0);assert.equal(exhausted,1);assert(scene.pausedByPlayer);assert.equal(lastHud.lives,0);
scene.setPaused(false);assert(scene.pausedByPlayer,'Cannot bypass exhausted lives with pause button');
const frozen=JSON.stringify(scene.run);scene.update(9000,50);assert.equal(JSON.stringify(scene.run),frozen,'All gameplay clocks freeze during the gate');
scene.continueRace();assert.equal(scene.lives,3);assert(!scene.pausedByPlayer);assert(scene.run.ghostUntil>scene.run.clock);
scene.run.charge=100;assert(scene.activateBoost());assert(!scene.activateBoost());scene.setPaused(true);assert(!scene.activateBoost());
console.log('PASS: perspective, biomes, speed, boost, collision, three lives, invincibility, pause and continuation.');
